import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar } from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
        
          <Navbar/>
          <div className={styles.textcontainer}>

          </div>
          <div className={styles.imgcontainer}>

          </div>
          <div className={styles.desc1}>

          </div>
          <div className={styles.desc2}>

          </div>
          <div className={styles.iconsContainer}>
            
            </div>
          <div className={styles.prev}>

          </div>
          <div className={styles.footer}>

          </div>
          </div>
       
        
       
      </main>
    </>
  );
}
